let sitcoms = [
  {
    title: "Brooklyn Nine-Nine",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/Brooklyn_Nine-Nine",
    imageUrl: "./images/broklyn99.jpg",
    trailerUrl: "https://www.youtube.com/embed/faJAT35j5Ss",
    desc: "Brooklyn Nine-Nine is a comedic American police sitcom created by Dan Goor and Michael Schur, who are the duo behind Parks and Recreation. The show is set in the fictional 99th Precinct in Brooklyn, and centres on Jake Peralta (Andy Samberg), a highly talented but immature NYPD detective who initially comes into conflict with his new commanding officer, the stern and ‘robotic’ Captain Raymond Holt (Andre Braugher).The first time I heard of Brooklyn Nine-Nine was when I stumbled across its hilarious Backstreet Boys cold open . When the show was suddenly cancelled in May last year, my best friend Katherine was shocked and devastated at the cancellation. After witnessing the immense online backlash against the cancellation and the rapid pick up by NBC the next day, I decided to watch an episode of the show. I didn’t think much of it at first, but choosing to watch the first episode of Brooklyn Nine-Nine has been one of the best decisions in my otherwise uneventful life.",
    watchNumber: 17,
    castUrl:
      "https://www.google.com/search?q=broklynn99+cast&sxsrf=ALiCzsYRr8df7W4epYlydHNqAECMclvLmA%3A1661580569711&ei=GbUJY4iCK9qp1e8P-tWMwAo&ved=0ahUKEwjI8v38reb5AhXaVPUHHfoqA6gQ4dUDCA4&uact=5&oq=broklynn99+cast&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA0yBAgAEA06BwgAEEcQsANKBAhBGABKBAhGGABQ0gRYwQVghghoAXABeACAAZEBiAGUApIBAzAuMpgBAKABAcgBCMABAQ&sclient=gws-wiz",
    cast: [
      {
        image: "./images/broklynnCast/1.jfif",
        name: "Andy Samberg",
        showName: "Detective Peralta",
        url: "https://en.wikipedia.org/wiki/Andy_Samberg",
      },
      {
        image: "./images/broklynnCast/2.jfif",
        name: "Melissa fumero",
        showName: "Amy Santiago",
        url: "https://en.wikipedia.org/wiki/Melissa_Fumero",
      },
      {
        image: "./images/broklynnCast/3.jfif",
        name: "Stephanie Betriaz",
        showName: "Detective Diaz",
        url: "https://en.wikipedia.org/wiki/Stephanie_Beatriz",
      },
      {
        image: "./images/broklynnCast/4.jfif",
        name: "Chelsea Peretti",
        showName: "Gina Linatti",
        url: "https://en.wikipedia.org/wiki/Chelsea_Peretti",
      },
      {
        image: "./images/broklynnCast/5.jfif",
        name: "Terry Crews",
        showName: "Lieutant Jeffords",
        url: "https://en.wikipedia.org/wiki/Terry_Crews",
      },
      {
        image: "./images/broklynnCast/6.jfif",
        name: "Andre Braugher",
        showName: "Captain Holt",
        url: "https://en.wikipedia.org/wiki/Andre_Braugher",
      },
      {
        image: "./images/broklynnCast/7.jfif",
        name: "Joe Lo Truglio",
        showName: "Charles Boyle",
        url: "https://en.wikipedia.org/wiki/Joe_Lo_Truglio",
      },
      {
        image: "./images/broklynnCast/8.jfif",
        name: "Jason Mantzoukas",
        showName: "Adrian Pimanto",
        url: "https://en.wikipedia.org/wiki/Jason_Mantzoukas",
      },
      {
        image: "./images/broklynnCast/9.jfif",
        name: "Joel Miller",
        showName: "Scully",
        url: "https://en.wikipedia.org/wiki/Joel_McKinnon_Miller",
      },
      {
        image: "./images/broklynnCast/10.jfif",
        name: "Marc Jackson",
        showName: "Dr.Kevin Cozner",
        url: "https://en.wikipedia.org/wiki/Marc_Evan_Jackson",
      },
      {
        image: "./images/broklynnCast/11.jfif",
        name: "Craig Robinson",
        showName: "Dough Judy",
        url: "https://en.wikipedia.org/wiki/Craig_Robinson_(actor)",
      },
      {
        image: "./images/broklynnCast/12.jfif",
        name: "Dirk Blocker",
        showName: "Michael Hitchcock",
        url: "https://en.wikipedia.org/wiki/Dirk_Blocker",
      },
    ],
  },
  {
    title: "Friends",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/Friends",
    imageUrl: "./images/friends.jpg",
    trailerUrl: "https://www.youtube.com/embed/RjpvuPAzJUw",
    desc: "The timeless television show of Friends was produced back on September 22nd, 1994 and continued airing until May 6th, 2004. It contains ten seasons of an American sitcom that can be described as comedic and relatable. It was produced by Kevin S. Bright, Marta Kauffman, and David Crane originally, with changes to the behind-the-camera crew changing over the years.In a Manhattan coffee shop, Central Perk, six friends come together to talk and live their lives in the Big Apple. Each character starts the show being in their early twenties, aging to their thirties throughout the course of the show. Some characters have been reunited over the years, and others have come together by fate. Love, friendships, occupations, and many other components of life are represented in this show.",
    watchNumber: 7,
    castUrl:
      "https://www.google.com/search?q=friends+cast&oq=friends+cast&aqs=chrome..69i57j0i433i512l2j0i512l7.2199j0j7&sourceid=chrome&ie=UTF-8",
    cast: [
      {
        image: "./images/friendsCast/1.jfif",
        name: "Jennifer Aniston",
        showName: "Rachel Green",
        url: "https://en.wikipedia.org/wiki/Jennifer_Aniston",
      },
      {
        image: "./images/friendsCast/2.jfif",
        name: "Courteney Cox",
        showName: "Monica Geller",
        url: "https://en.wikipedia.org/wiki/Courteney_Cox",
      },
      {
        image: "./images/friendsCast/3.jfif",
        name: "Matthew Perry",
        showName: "Chandler Bing",
        url: "https://en.wikipedia.org/wiki/Matthew_Perry",
      },
      {
        image: "./images/friendsCast/4.jfif",
        name: "David Schwimmer",
        showName: "Ross Geller",
        url: "https://en.wikipedia.org/wiki/David_Schwimmer",
      },
      {
        image: "./images/friendsCast/5.jfif",
        name: "Matt LeBlanc",
        showName: "Joey Tribbiani",
        url: "https://en.wikipedia.org/wiki/Matt_LeBlanc",
      },
      {
        image: "./images/friendsCast/6.jfif",
        name: "Lisa Kudrow",
        showName: "Phoebe Buffay",
        url: "https://en.wikipedia.org/wiki/Lisa_Kudrow",
      },
    ],
  },
  {
    title: "Modern Family",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/Modern_Family",
    imageUrl: "./images/modernFamily.jpg",
    trailerUrl: "https://www.youtube.com/embed/X0lRjbrH-L8",
    desc: "The Pritchett-Dunphy-Tucker clan is a wonderfully large and blended family with Jay Pritchett (Ed O'Neil) sitting at the head. By his side is his vivacious, younger second wife, Gloria (Sofia Vergara), and together they are navigating life with their youngest son, Joe, and Gloria's son, Manny (Rico Rodriguez), who is heading off to college to explore the world on his own terms. Meanwhile, Jay's grown daughter, Claire (Julie Bowen), and her husband, Phil (Ty Burrell), are learning to navigate life as empty-nesters with the youngest, Luke (Nolan Gould), now out of high school and looking to his next move; middle daughter Alex (Ariel Winter) is learning how to balance academia and a social life, and eldest Haley (Sarah Hyland) is still living at home as she pursues a career and love. Then there's Claire's brother and Jay's grown son, Mitchell (Jesse Tyler Ferguson), and his husband, Cameron (Eric Stonestreet), who are about to enter the dreaded middle-school years with their newly discovered, gifted daughter, Lily (Aubrey Anderson-Emmons). These three families are unique unto themselves, and together they give us an honest and often hilarious look into the sometimes warm, sometimes twisted, embrace of the modern family.",
    watchNumber: 6,
    castUrl:
      "https://www.google.com/search?q=modern+family+cast&oq=modern+family+cast&aqs=chrome..69i57j0i20i131i263i433i512j0i512l6j46i512j0i512.2447j0j4&sourceid=chrome&ie=UTF-8",
    cast: [
      {
        image: "./images/modernFamilyCast/1.jfif",
        name: "Sarah Hyland",
        showName: "Haley Dunphy",
        url: "https://en.wikipedia.org/wiki/Sarah_Hyland",
      },
      {
        image: "./images/modernFamilyCast/2.jfif",
        name: "Sofia Vergara",
        showName: "Gloria Pritchett",
        url: "https://en.wikipedia.org/wiki/Sof%C3%ADa_Vergara",
      },
      {
        image: "./images/modernFamilyCast/3.jfif",
        name: "Ariel Winter",
        showName: "Alex Dunphy",
        url: "https://en.wikipedia.org/wiki/Ariel_Winter",
      },
      {
        image: "./images/modernFamilyCast/4.jfif",
        name: "Julie Bowen",
        showName: "Claire Dunphy",
        url: "https://en.wikipedia.org/wiki/Julie_Bowen",
      },
      {
        image: "./images/modernFamilyCast/5.jfif",
        name: "ty Burell",
        showName: "Phil Dunphy",
        url: "https://en.wikipedia.org/wiki/Ty_Burrell",
      },
      {
        image: "./images/modernFamilyCast/6.jfif",
        name: "Eric Stonestreet",
        showName: "Cameron Tucker",
        url: "https://en.wikipedia.org/wiki/Eric_Stonestreet",
      },
      {
        image: "./images/modernFamilyCast/7.jfif",
        name: "Nolan Gould",
        showName: "luke Dunphy",
        url: "https://en.wikipedia.org/wiki/Nolan_Gould",
      },
      {
        image: "./images/modernFamilyCast/8.jfif",
        name: "Jesse ferguson",
        showName: "Mitchell Prtichett",
        url: "https://en.wikipedia.org/wiki/Jesse_Tyler_Ferguson",
      },
      {
        image: "./images/modernFamilyCast/9.jfif",
        name: "Rico Rodriguez",
        showName: "Manny Delgado",
        url: "https://en.wikipedia.org/wiki/Rico_Rodriguez_(actor)",
      },
      {
        image: "./images/modernFamilyCast/10.jfif",
        name: "Aubrey Anderson",
        showName: "Lily Pritchett",
        url: "https://en.wikipedia.org/wiki/Aubrey_Anderson-Emmons",
      },
      {
        image: "./images/modernFamilyCast/11.jfif",
        name: "Ed O'Neil",
        showName: "Jay Pritchett",
        url: "https://en.wikipedia.org/wiki/Ed_O%27Neill",
      },
      {
        image: "./images/modernFamilyCast/12.jfif",
        name: "Reid Ewing",
        showName: "Dylan",
        url: "https://en.wikipedia.org/wiki/Reid_Ewing",
      },
      {
        image: "./images/modernFamilyCast/13.jfif",
        name: "Jeremy Maguire",
        showName: "Joe Pritchett",
        url: "https://en.wikipedia.org/wiki/Jeremy_Maguire",
      },
    ],
  },
  {
    title: "Big Bang Theory",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/The_Big_Bang_Theory",
    imageUrl: "./images/bbt.jfif",
    trailerUrl: "https://www.youtube.com/embed/RJknrSi3eUQ",
    desc: "The Big Bang Theory was an American sitcom from Chuck Lorre Productions and Warner Bros. Television that ran for twelve seasons on CBS.The Big Bang Theory premiered on September 24, 2007, and the hour-long series finale aired Thursday, May 16, 2019.The Big Bang Theory starred Jim Parsons, Johnny Galecki, Kaley Cuoco, Simon Helberg, Kunal Nayyar, Mayim Bialik and Melissa Rauch. The Big Bang Theory was created by Chuck Lorre and Bill Prady.The Big Bang Theory was centered on physicists Sheldon Cooper and Leonard Hofstadter, whose geeky and introverted lives were changed when Penny, an attractive waitress and aspiring actress, moved into the apartment across from theirs. Penny quickly became a part of Sheldon and Leonard's social group, which included the equally geeky engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The group later expanded to include Howard's wife Bernadette Rostenkowski-Wolowitz and Sheldon's wife Amy Farrah Fowler.",
    watchNumber: 4,
    castUrl:
      "https://www.google.com/search?q=big+bang+theory+cast&oq=big+bang+theory+cast&aqs=chrome.0.0i20i263i512j0i512l9.2351j0j4&sourceid=chrome&ie=UTF-8",
    cast: [
      {
        image: "./images/bbtCast/1.jfif",
        name: "kaley Couco",
        showName: "Penny",
        url: "https://en.wikipedia.org/wiki/Kaley_Cuoco",
      },
      {
        image: "./images/bbtCast/2.jfif",
        name: "Jim parsons",
        showName: "Sheldon Cooper",
        url: "https://en.wikipedia.org/wiki/Jim_Parsons",
      },
      {
        image: "./images/bbtCast/3.jfif",
        name: "Melissa Rauch",
        showName: "Bernadette",
        url: "https://en.wikipedia.org/wiki/Melissa_Rauch",
      },
      {
        image: "./images/bbtCast/4.jfif",
        name: "Mayim Bialik",
        showName: "Amy Fowler",
        url: "https://en.wikipedia.org/wiki/Mayim_Bialik",
      },
      {
        image: "./images/bbtCast/5.jfif",
        name: "Johnny Galecki",
        showName: "Leonard",
        url: "https://en.wikipedia.org/wiki/Johnny_Galecki",
      },
      {
        image: "./images/bbtCast/6.jfif",
        name: "Simon Helberg",
        showName: "Howard",
        url: "https://en.wikipedia.org/wiki/Simon_Helberg",
      },
      {
        image: "./images/bbtCast/7.jfif",
        name: "Kunal Nayyar",
        showName: "rajesh",
        url: "https://en.wikipedia.org/wiki/Kunal_Nayyar",
      },
    ],
  },
  {
    title: "The Office",
    sitcomWikiUrl:
      "https://en.wikipedia.org/wiki/The_Office_(American_TV_series)",
    imageUrl: "./images/to.jpg",
    trailerUrl: "https://www.youtube.com/embed/LHOtME2DL4g",
    desc: "NBC's smash hit sitcom The Office captivated audiences as it unfolded in a nine-season run from 2005 to 2013. During that eight-year stretch, the simple premise of the series — documenting life in a typical American workspace — grew into a massive story with numerous twists, subplots, romances, and side characters. When all was said and done, the show boasted more than 200 episodes, all filled to the brink with storytelling at its finest. The truth is, though, while this gigantic pile of entertainment is incredibly fun to binge over and over again, it can be a bit difficult to follow the greater storyline at times. With so many dynamic personalities co-existing in one tiny office building, it's easy to get lost in the details. So we've gone ahead and mapped things out in a sweet and condensed format in order to finally allow fans to step back and get that 10,000-foot view of what exactly happened during the eight years that America's favorite workplace was under the scrutiny of a PBS documentary crew.",
    watchNumber: 4,
    castUrl:
      "https://www.google.com/search?q=the+office+cast&oq=the+office+cast&aqs=chrome.0.69i59j0i512l9.1989j0j4&sourceid=chrome&ie=UTF-8",
    cast: [
      {
        image: "./images/toCast/1.jfif",
        name: "Steve Carell",
        showName: "Michael Scott",
        url: "https://en.wikipedia.org/wiki/Steve_Carell",
      },
      {
        image: "./images/toCast/2.jfif",
        name: "John Krasinski",
        showName: "Jim halpert",
        url: "https://en.wikipedia.org/wiki/John_Krasinski",
      },
      {
        image: "./images/toCast/3.jfif",
        name: "Jenna Fischser",
        showName: "Pam Beesly",
        url: "https://en.wikipedia.org/wiki/Jenna_Fischer",
      },
      {
        image: "./images/toCast/4.jfif",
        name: "Rainn Wilson",
        showName: "Dwight Schrute",
        url: "https://en.wikipedia.org/wiki/Rainn_Wilson",
      },
      {
        image: "./images/toCast/5.jfif",
        name: "Ellie Kemper",
        showName: "Erin Hannon",
        url: "https://en.wikipedia.org/wiki/Ellie_Kemper",
      },
      {
        image: "./images/toCast/6.jfif",
        name: "Angela kinsky",
        showName: "Angela Martin",
        url: "https://en.wikipedia.org/wiki/Angela_Kinsey",
      },
      {
        image: "./images/toCast/7.jfif",
        name: "Mindy Kaling",
        showName: "Kelly kapoor",
        url: "https://en.wikipedia.org/wiki/Mindy_Kaling",
      },
      {
        image: "./images/toCast/8.jfif",
        name: "B. J. Novak",
        showName: "Ryan Howard",
        url: "https://en.wikipedia.org/wiki/B._J._Novak",
      },
      {
        image: "./images/toCast/9.jfif",
        name: "Melora Hardin",
        showName: "Jan Levinson",
        url: "https://en.wikipedia.org/wiki/Melora_Hardin",
      },
      {
        image: "./images/toCast/10.jfif",
        name: "Rashida Jones",
        showName: "Karein",
        url: "https://en.wikipedia.org/wiki/Rashida_Jones",
      },
      {
        image: "./images/toCast/11.jfif",
        name: "Ed Helms",
        showName: "Andy Bernard",
        url: "https://en.wikipedia.org/wiki/Ed_Helms",
      },
      {
        image: "./images/toCast/12.jfif",
        name: "Creed Bratton",
        showName: "Creed Bratton",
        url: "https://en.wikipedia.org/wiki/Creed_Bratton",
      },
      {
        image: "./images/toCast/13.jfif",
        name: "Oscar Nunez",
        showName: "Oscar Martinez",
        url: "https://en.wikipedia.org/wiki/Oscar_Nunez",
      },
      {
        image: "./images/toCast/14.jfif",
        name: "Brian Baumgartner",
        showName: "Kevin Malone",
        url: "https://en.wikipedia.org/wiki/Brian_Baumgartner",
      },
      {
        image: "./images/toCast/15.jfif",
        name: "Phyllis Smith",
        showName: "Phyllis Vance",
        url: "https://en.wikipedia.org/wiki/Phyllis_Smith",
      },
      {
        image: "./images/toCast/16.jfif",
        name: "Amy Ryan",
        showName: "Holly Flex",
        url: "https://en.wikipedia.org/wiki/Amy_Ryan",
      },
    ],
  },
  {
    title: "How I Mate Your Mother",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/How_I_Met_Your_Mother",
    imageUrl: "./images/himym.jfif",
    trailerUrl: "https://www.youtube.com/embed/HdcxGbX0W_U",
    desc: "How I Met Your Mother is an American Sitcom that premiered on CBS on September 19, 2005. The show was created by Craig Thomas and Carter Bays. The season nine finale aired on March 31, 2014 on CBS. [1]The series revolves around Ted Mosby (Josh Radnor) who in the year of 2030 tells the story to his son and daughter how he met their mother (hence the title). While living in New York City and working as an architect, the narrative deals with his best friends, including the long-lasting couple Marshall Eriksen (Jason Segel) and Lily Aldrin (Alyson Hannigan); the eccentric, womanizer-playboy Barney Stinson (Neil Patrick Harris); and news anchor Robin Scherbatsky (Cobie Smulders). The series explores many storylines, including a love triangle between Robin, Ted, and Barney; Marshall and Lily's relationship; as well as the careers of the characters and so much more. The series is narrated by Bob Saget through flashbacks from the future.",
    watchNumber: 2,
    castUrl:
      "https://www.google.com/search?q=how+i+mate+your+mother+cast&oq=how+i+mate+your+mother+cast&aqs=chrome..69i57j0i13l9.4335j0j4&sourceid=chrome&ie=UTF-8",
    cast: [
      {
        image: "./images/himymCast/1.jfif",
        name: "Josh Radnor",
        showName: "Ted Mosby",
        url: "https://en.wikipedia.org/wiki/Josh_Radnor",
      },
      {
        image: "./images/himymCast/2.jfif",
        name: "Neil Patrick Harris",
        showName: "Barney Stinson",
        url: "https://en.wikipedia.org/wiki/Neil_Patrick_Harris",
      },
      {
        image: "./images/himymCast/3.jfif",
        name: "Cobie Smulders",
        showName: "Robin Scherbatsky",
        url: "https://en.wikipedia.org/wiki/Cobie_Smulders",
      },
      {
        image: "./images/himymCast/4.jfif",
        name: "Alyson Hannigan",
        showName: "Lily Aldrin",
        url: "https://en.wikipedia.org/wiki/Alyson_Hannigan",
      },
      {
        image: "./images/himymCast/5.jfif",
        name: "Jason Segel",
        showName: "Marshall Eriksen",
        url: "https://en.wikipedia.org/wiki/Jason_Segel",
      },
      {
        image: "./images/himymCast/6.jfif",
        name: "Cristin Milioti",
        showName: "The Mother",
        url: "https://en.wikipedia.org/wiki/Cristin_Milioti",
      },
    ],
  },
  {
    title: "Two And Half Men",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/Two_and_a_Half_Men",
    imageUrl: "./images/tahm.jpg",
    trailerUrl: "https://www.youtube.com/embed/097pUW0L_Xc",
    desc: "The first eight seasons of Two and a Half Men follows Charlie Harper, a hedonistic jingle writer living in a beachfront Malibu abode, whose life is turned upside down when his brother Alan comes to live with him following a divorce, coupled with his nephew Jake visiting on the weekends. Charlie's ability to coast through life coupled with Alan's excessively uptight nature lead to them butting heads frequently. From the ninth season, Charlie dies while living overseas, and his house is bought by Internet billionaire Walden Schmidt. However, rather than kick Charlie and Jake out, he invites them to live with him, and the three form something of a makeshift family.",
    watchNumber: 4,
    castUrl:
      "https://www.google.com/search?q=two+and+a+half+men+cast&oq=two+and+a+half+men+cast&aqs=chrome.0.69i59j0i512l6j0i390l3.2811j0j4&sourceid=chrome&ie=UTF-8",
    cast: [
      {
        image: "./images/tahmCast/1.jfif",
        name: "Charlie Sheen",
        showName: "Charlie Harper",
        url: "https://en.wikipedia.org/wiki/Charlie_Sheen",
      },
      {
        image: "./images/tahmCast/2.jfif",
        name: "Jon Cryer",
        showName: "Alan Harper",
        url: "https://en.wikipedia.org/wiki/Jon_Cryer",
      },
      {
        image: "./images/tahmCast/3.jfif",
        name: "Angus Jones",
        showName: "Jake Harper",
        url: "https://en.wikipedia.org/wiki/Angus_T._Jones",
      },
      {
        image: "./images/tahmCast/4.jfif",
        name: "Ashton Kutcher",
        showName: "Walden Schmidt",
        url: "https://en.wikipedia.org/wiki/Ashton_Kutcher",
      },
      {
        image: "./images/tahmCast/5.jfif",
        name: "Melanie Lynskey",
        showName: "Rose",
        url: "https://en.wikipedia.org/wiki/Melanie_Lynskey",
      },
      {
        image: "./images/tahmCast/6.jfif",
        name: "Marin Hinkle",
        showName: "Judith Harper",
        url: "https://en.wikipedia.org/wiki/Marin_Hinkle",
      },
      {
        image: "./images/tahmCast/7.jfif",
        name: "Holand Taylor",
        showName: "Evelyn Harper",
        url: "https://en.wikipedia.org/wiki/Holland_Taylor",
      },
      {
        image: "./images/tahmCast/8.jfif",
        name: "Conchatta Ferrell",
        showName: "Berta",
        url: "https://en.wikipedia.org/wiki/Conchata_Ferrell",
      },
    ],
  },
  {
    title: "Game Of Thrones",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/Game_of_Thrones",
    imageUrl: "./images/got.jpg",
    trailerUrl: "https://www.youtube.com/embed/KPLWWIOCOOQ",
    desc: "Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. It is an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones. The show was shot in the United Kingdom, Canada, Croatia, Iceland, Malta, Morocco, and Spain. It premiered on HBO in the United States on April 17, 2011, and concluded on May 19, 2019, with 73 episodes broadcast over eight seasons.Set on the fictional continents of Westeros and Essos, Game of Thrones has a large ensemble cast and follows several story arcs throughout the course of the show. The first major arc concerns the Iron Throne of the Seven Kingdoms of Westeros through a web of political conflicts among the noble families either vying to claim the throne or fighting for independence from whoever sits on it. A second focuses on the last descendant of the realm's deposed ruling dynasty, who has been exiled to Essos and is plotting to return and reclaim the throne. The third follows the Night's Watch, a military order defending the realm against threats from beyond Westeros's northern border.",
    watchNumber: 2,
    castUrl:
      "https://www.google.com/search?q=game+of+thrones+cast&sxsrf=ALiCzsanNAuhcbaZeYzIAEGVeDbn-WqRRQ%3A1661587591614&ei=h9AJY5GRJdTBhwOqjaboBw&ved=0ahUKEwjR8KSRyOb5AhXU4GEKHaqGCX0Q4dUDCA4&uact=5&oq=game+of+thrones+cast&gs_lcp=Cgdnd3Mtd2l6EAMyCwgAEIAEELEDEIMBMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEOgcIABBHELADOgoILhCxAxCDARBDOggIABCxAxCRAjoKCAAQsQMQgwEQQzoLCC4QgAQQsQMQgwE6CAgAELEDEIMBOgoIABCABBCHAhAUOggIABCABBCxAzoFCAAQkQI6BQguEIAEOgYIABAeEBZKBAhBGABKBAhGGABQvwRYsxNg5BRoAnABeACAAZcBiAGPCpIBBDAuMTCYAQCgAQHIAQjAAQE&sclient=gws-wiz",
    cast: [],
  },
  {
    title: "Naruto",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/Naruto",
    imageUrl: "./images/naruto.jpg",
    trailerUrl: "https://www.youtube.com/embed/-G9BqkgZXRA",
    desc: "Naruto[a] is a Japanese manga series written and illustrated by Masashi Kishimoto. It tells the story of Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village. The story is told in two parts – the first set in Naruto's pre-teen years, and the second in his teens. The series is based on two one-shot manga by Kishimoto: Karakuri (1995), which earned Kishimoto an honorable mention in Shueisha's monthly Hop Step Award the following year, and Naruto (1997).",
    watchNumber: 2,
    castUrl:
      "https://www.google.com/search?q=baruto+cast&oq=baruto+cast&aqs=chrome..69i57j0i10i131i433j0i10l8.1716j0j4&sourceid=chrome&ie=UTF-8",
    cast: [],
  },
  {
    title: "Breaking Bad",
    sitcomWikiUrl: "https://en.wikipedia.org/wiki/Breaking_Bad",
    imageUrl: "./images/bb.jpeg",
    trailerUrl: "https://www.youtube.com/embed/HhesaQXLuRY",
    desc: "When chemistry teacher Walter White is diagnosed with Stage III cancer and given only two years to live, he decides he has nothing to lose. He lives with his teenage son, who has cerebral palsy, and his wife, in New Mexico. Determined to ensure that his family will have a secure future, Walt embarks on a career of drugs and crime. He proves to be remarkably proficient in this new world as he begins manufacturing and selling methamphetamine with one of his former students. The series tracks the impacts of a fatal diagnosis on a regular, hard working man, and explores how a fatal diagnosis affects his morality and transforms him into a major player of the drug trade.",
    watchNumber: 2,
    castUrl:
      "https://www.google.com/search?q=breaking+bad+cast&oq=breaking+bad+cast&aqs=chrome.0.0i20i131i263i433i512j0i512l9.1915j0j4&sourceid=chrome&ie=UTF-8",
    cast: [
      {
        image: "./images/bbCast/1.jfif",
        name: "Bryan Cranston",
        showName: "Walter White",
        url: "https://en.wikipedia.org/wiki/Bryan_Cranston",
      },
      {
        image: "./images/bbCast/2.jfif",
        name: "Aaron Paul",
        showName: "Jesse Pinkman",
        url: "https://en.wikipedia.org/wiki/Aaron_Paul",
      },
      {
        image: "./images/bbCast/3.jfif",
        name: "Anna Gunn",
        showName: "Skyler White",
        url: "https://en.wikipedia.org/wiki/Anna_Gunn",
      },
      {
        image: "./images/bbCast/4.jfif",
        name: "RJ Mitte",
        showName: "Walter White Jr.",
        url: "https://en.wikipedia.org/wiki/RJ_Mitte",
      },
      {
        image: "./images/bbCast/5.jfif",
        name: "Dean Norris",
        showName: "Hank Schrader",
        url: "https://en.wikipedia.org/wiki/Dean_Norris",
      },
      {
        image: "./images/bbCast/6.jfif",
        name: "Bob Odenkirk",
        showName: "Saul Goodman",
        url: "https://en.wikipedia.org/wiki/Bob_Odenkirk",
      },
      {
        image: "./images/bbCast/7.jfif",
        name: "Jonathan Banks",
        showName: "Mike Erhmantraut",
        url: "https://en.wikipedia.org/wiki/Jonathan_Banks",
      },
      {
        image: "./images/bbCast/8.jfif",
        name: "Giancarlo Esposito",
        showName: "Gus Fring",
        url: "https://en.wikipedia.org/wiki/Giancarlo_Esposito",
      },
    ],
  },
];

export { sitcoms };
